### ISSUE TITLE
Is there a FOS pathway to generating the adjacency matrix in the paper:

### ISSUE THREAD

**Issue by russelljjarvis** [Hippocampome-Org/GraphTheory#1]
Regarding the paper and associated work graph-theoretic and motif analyses of the hippocampal neuron type potential connectome
http://www.eneuro.org/content/early/2016/11/07/ENEURO.0205-16.2016

Can Ie I run octave on the *.m files and generate a large adjacency matrix? Also where does the data from that paper come from?
The paper refers to this link, but its unclear how to use curl or python to download the csv or other data that constitutes the matrix that is displayed.
http://hippocampome.org/php/morphology.php?refreshed

**Comment by ChristopherRees** [comment]
Hi Russell, 

Thanks very much for your question and interest in our data.  We are more than happy to make our data and source code freely and publically available.

As to where the data comes from, the collection procedures and potential uses are detailed in [this article](https://elifesciences.org/articles/09960).  Briefly, we combed the literature and found enough evidence to initially instantiate 122 **cell types** in the neuron hippocampus.  When the _axons_ of one type are found in the same parcel (i.e. hippocampal sub-region and layer) as the _dendrites_ of another, these types are **potentially connected** and are marked as such in the adjacency matrix (in the paper you reference and available [online](http://hippocampome.org/php/connectivity.php)).  Thus, the adjacency matrix is derived from the  [morphology matrix](http://hippocampome.org/php/morphology.php) by looking for overlaps of axons and dendrites among types within any parcel.  These potential connections may then be confirmed (green + signs in the matrix) or refuted (red x) by experimental evidence.

The netlist for these connections can be downloaded [here](http://hippocampome.org/netlist).  I am also attaching an XLSX adjacency matrix (below) that uses the following key:

2 = confirmed excitatory connection
1 = potential excitatory connection
0 = no connection (either no potential connection OR potential connection was refuted)
-1 = potential inhibitory connection
-2 = confirmed inhibitory connection

Please let me know if you have additional questions.

Thanks again, 
Christopher

[_hybrid_connectivity_matrix_20171103_092033.xlsx](https://github.com/Hippocampome-Org/GraphTheory/files/1657258/_hybrid_connectivity_matrix_20171103_092033.xlsx)

**Comment by russelljjarvis** [comment]
Hi Christopher, 

Thanks for this elaborate response.

**Comment by drdiek** [comment]
Russel,


By my count, there are 38 excitatory neuron types, out of 122 total.


Sincerely,


Diek

________________________________
